server_stuffs/todoserver/config/routes.rb
Todoserver::Application.routes.draw do
  resources :users do
    resources :groups do
      resources :tododetails do
      end
    end

    resources :sent_invitations do
    end

    resources :recv_invitations do
    end
  end

  resources :groups do
    resources :tododetails do
    end

    resources :users do
    end
  end

  resources :tododetails do
  end

  get "users/:id/unsubscribe" => "users#unsubscribe"

  get "/users/:user_id/recv_invitations/:inv_id/accept" => "recv_invitations#accept"
  get "/users/:user_id/recv_invitations/:inv_id/reject" => "recv_invitations#reject"

  get "home/index"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

end

server_stuffs/todoserver/app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tododetails, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => true
  validate :description

#  attr_accessible :name => true
#  attr_accessible :description => true
end

server_stuffs/todoserver/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    if params[:user_id].nil? == false:
      @groups = User.find(params[:user_id]).groups

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @groups }
        format.json  { render :json => @groups }
      end
    else
      @groups = Group.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @groups }
      end
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
      format.json { render :json => @group } 
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
      format.json { render :json => @group } 
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @user = User.find(params[:user_id])
    @group = @user.groups.create(:name => params[:group][:name], :description => params[:group][:description])

    respond_to do |format|
      format.html { redirect_to(@user, :notice => 'Group was successfully created.') }
      format.xml  { render :xml => @group, :status => :created, :location => @group }
      format.json  { render :json => @group, :status => :created, :location => @group }

      # TODO
      if true == false:
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
        format.json  { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
end

server_stuffs/todoserver/app/helpers/groups_helper.rb
module GroupsHelper
end

server_stuffs/todoserver/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server_stuffs/todoserver/app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

server_stuffs/todoserver/app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

server_stuffs/todoserver/app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

server_stuffs/todoserver/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<h2>Users</h2>
<% @group.users.each do |user| %>
  <p>
    <b>User Name:</b>
    <%= user.name %>
  </p>
<% end %>

<h2>Todos</h2>
<% @group.tododetails.each do |todo| %>
  <p>
    <b>Name:</b>
    <%= todo.title %>
  </p>
  <p>
    <b>Place:</b>
    <%= todo.place %>
  </p>
  <p>
    <b>Note:</b>
    <%= todo.note %>
  </p>
  <p>
    <b>Tag:</b>
    <%= todo.tag %>
  </p>
  <p>
    <b>Status:</b>
    <%= todo.status %>
  </p>
  <p>
    <b>Priority:</b>
    <%= todo.priority %>
  </p>
  <p>
    <b>Deadline:</b>
    <%= todo.deadline %>
  </p>

  <p>
    <%= link_to 'Delete todo', [todo.group, todo],
                 :confirm => 'Are you sure?',
                 :method => :delete %>
  </p>
<% end %>

<h2>Add a Todo</h2>
<%= form_for([@group, @group.tododetails.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.text_field :deadline %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>