server_stuffs/server_checkpoint/config/routes.rb
Todoserver::Application.routes.draw do

  resources :tododetails
  resources :entries

  get "home/index"

  root :to => "home#index"

end

server_stuffs/server_checkpoint/app/models/entry.rb
class Entry < ActiveRecord::Base
end

server_stuffs/server_checkpoint/app/models/tododetail.rb
class Tododetail < ActiveRecord::Base
end

server_stuffs/server_checkpoint/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

server_stuffs/server_checkpoint/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.xml
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.xml
  def show
#    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entry }
      format.json { render :json => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.xml
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entry }
      format.json { render :json => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.xml
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to(@entry, :notice => 'Entry was successfully created.') }
        format.xml  { render :xml => @entry, :status => :created, :location => @entry }
	format.json { render :json => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
	format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.xml
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to(@entry, :notice => 'Entry was successfully updated.') }
        format.xml  { head :ok }
	format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry.errors, :status => :unprocessable_entity }
	format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.xml
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to(entries_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
end

server_stuffs/server_checkpoint/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

server_stuffs/server_checkpoint/app/controllers/tododetails_controller.rb
class TododetailsController < ApplicationController
  # GET /tododetails
  # GET /tododetails.xml
  def index
    @tododetails = Tododetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tododetails }
    end
  end

  # GET /tododetails/1
  # GET /tododetails/1.xml
  def show
    @tododetail = Tododetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tododetail }
    end
  end

  # GET /tododetails/new
  # GET /tododetails/new.xml
  def new
    @tododetail = Tododetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tododetail }
      format.json { render :json => @tododetail }
    end
  end

  # GET /tododetails/1/edit
  def edit
    @tododetail = Tododetail.find(params[:id])
  end

  # POST /tododetails
  # POST /tododetails.xml
  def create
    @tododetail = Tododetail.new(params[:tododetail])

    respond_to do |format|
      if @tododetail.save
        format.html { redirect_to(@tododetail, :notice => 'Tododetail was successfully created.') }
        format.xml  { render :xml => @tododetail, :status => :created, :location => @tododetail }
	format.json { render :json => @tododetail, :status => :created, :location => @tododetail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tododetail.errors, :status => :unprocessable_entity }
	format.json { render :json => @tododetail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tododetails/1
  # PUT /tododetails/1.xml
  def update
    @tododetail = Tododetail.find(params[:id])

    respond_to do |format|
      if @tododetail.update_attributes(params[:tododetail])
        format.html { redirect_to(@tododetail, :notice => 'Tododetail was successfully updated.') }
        format.xml  { head :ok }
	format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tododetail.errors, :status => :unprocessable_entity }
	format.json { render :json => @tododetail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tododetails/1
  # DELETE /tododetails/1.xml
  def destroy
    @tododetail = Tododetail.find(params[:id])
    @tododetail.destroy

    respond_to do |format|
      format.html { redirect_to(tododetails_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
end

server_stuffs/server_checkpoint/app/helpers/application_helper.rb
module ApplicationHelper
end

server_stuffs/server_checkpoint/app/helpers/entries_helper.rb
module EntriesHelper
end

server_stuffs/server_checkpoint/app/helpers/home_helper.rb
module HomeHelper
end

server_stuffs/server_checkpoint/app/helpers/tododetails_helper.rb
module TododetailsHelper
end

server_stuffs/server_checkpoint/app/views/tododetails/_form.html.erb
<%= form_for(@tododetail) do |f| %>
  <% if @tododetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tododetail.errors.count, "error") %> prohibited this tododetail from being saved:</h2>

      <ul>
      <% @tododetail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todo %><br />
    <%= f.text_field :todo %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_area :tag %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :delivered %><br />
    <%= f.text_field :delivered %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server_stuffs/server_checkpoint/app/views/tododetails/edit.html.erb
<h1>Editing tododetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @tododetail %> |
<%= link_to 'Back', tododetails_path %>

server_stuffs/server_checkpoint/app/views/tododetails/index.html.erb
<h1>Listing tododetails</h1>

<table>
  <tr>
    <th>Todo</th>
    <th>Place</th>
    <th>Note</th>
    <th>Tag</th>
    <th>Group</th>
    <th>Status</th>
    <th>Delivered</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tododetails.each do |tododetail| %>
  <tr>
    <td><%= tododetail.todo %></td>
    <td><%= tododetail.place %></td>
    <td><%= tododetail.note %></td>
    <td><%= tododetail.tag %></td>
    <td><%= tododetail.group %></td>
    <td><%= tododetail.status %></td>
    <td><%= tododetail.delivered %></td>
    <td><%= link_to 'Show', tododetail %></td>
    <td><%= link_to 'Edit', edit_tododetail_path(tododetail) %></td>
    <td><%= link_to 'Destroy', tododetail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tododetail', new_tododetail_path %>

server_stuffs/server_checkpoint/app/views/tododetails/new.html.erb
<h1>New tododetail</h1>

<%= render 'form' %>

<%= link_to 'Back', tododetails_path %>

server_stuffs/server_checkpoint/app/views/tododetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Todo:</b>
  <%= @tododetail.todo %>
</p>

<p>
  <b>Place:</b>
  <%= @tododetail.place %>
</p>

<p>
  <b>Note:</b>
  <%= @tododetail.note %>
</p>

<p>
  <b>Tag:</b>
  <%= @tododetail.tag %>
</p>

<p>
  <b>Group:</b>
  <%= @tododetail.group %>
</p>

<p>
  <b>Status:</b>
  <%= @tododetail.status %>
</p>

<p>
  <b>Delivered:</b>
  <%= @tododetail.delivered %>
</p>


<%= link_to 'Edit', edit_tododetail_path(@tododetail) %> |
<%= link_to 'Back', tododetails_path %>